### ISSUE TITLE
WingsNet中注意力模块的疑惑

### ISSUE THREAD

**Issue by Itsanewday** [haozheng-sjtu/3d-airway-segmentation#11]
作者您好，首先感谢公开支气管分割框架，对我帮助很大！看了您的《Alleviating Class-wise Gradient Imbalance for
Pulmonary Airway Segmentation》后，在网络设计方面有一些疑惑: 您参考的论文将SE拓展为cSE(原始的), sSE(WingsNet采用的）和scSE(二者结合)，参考的论文中做过一些对照实验，结果表明第三类变种在医学分割任务中性能最好，
![image](https://user-images.githubusercontent.com/21170245/217994832-e9244080-5c17-448f-a026-d62de32bee0a.png)

您在WingsNet中为什么采用sSE而不是scSE呢？

**Comment by haozheng-sjtu** [comment]
3D的中间结果太占显存了，所以原始分辨率的层就用简单的，下采样后可以用更复杂的。 


发件人: "Itsanewday" ***@***.***> 
收件人: "haozheng-sjtu/3d-airway-segmentation" ***@***.***> 
抄送: "Subscribed" ***@***.***> 
发送时间: 星期五, 2023年 2 月 10日 上午 11:37:37 
主题: [haozheng-sjtu/3d-airway-segmentation] WingsNet中注意力模块的疑惑 (Issue #11) 





作者您好，首先感谢公开支气管分割框架，对于我的帮助很大！看了您的《Alleviating Class-wise Gradient Imbalance for 
Pulmonary Airway Segmentation》后，在网络设计方面有一些疑惑，您参考的论文将SE拓展为cSE(原始的), sSE(WingsNet采用的）和scSE(二者结合）的，参考的论文中做过一些对照实验，结果表明第三类变种在医学分割任务中性能最好，您在WingsNet中为什么采用sSE而不是scSE呢？

**Comment by Itsanewday** [comment]
确实，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月16日(周四) 晚上8:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [haozheng-sjtu/3d-airway-segmentation] WingsNet中注意力模块的疑惑 (Issue #11)




 3D的中间结果太占显存了，所以原始分辨率的层就用简单的，下采样后可以用更复杂的。 
 
 
 发件人: "Itsanewday" ***@***.***&gt; 
 收件人: "haozheng-sjtu/3d-airway-segmentation" ***@***.***&gt; 
 抄送: "Subscribed" ***@***.***&gt; 
 发送时间: 星期五, 2023年 2 月 10日 上午 11:37:37 
 主题: [haozheng-sjtu/3d-airway-segmentation] WingsNet中注意力模块的疑惑 (Issue #11) 
 
 
 
 
 
 作者您好，首先感谢公开支气管分割框架，对于我的帮助很大！看了您的《Alleviating Class-wise Gradient Imbalance for 
 Pulmonary Airway Segmentation》后，在网络设计方面有一些疑惑，您参考的论文将SE拓展为cSE(原始的), sSE(WingsNet采用的）和scSE(二者结合）的，参考的论文中做过一些对照实验，结果表明第三类变种在医学分割任务中性能最好，您在WingsNet中为什么采用sSE而不是scSE呢？
